# Generated by Django 4.1.3 on 2022-11-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название')),
                ('image', models.ImageField(upload_to='pizzaName', verbose_name='Картинка')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('modalContent', models.TextField(blank='True', verbose_name='Описание')),
                ('isMeat', models.PositiveIntegerField(verbose_name='Тип пиццы(0/1)')),
                ('popularity', models.PositiveIntegerField(verbose_name='Популярность')),
                ('date_create', models.CharField(max_length=10, verbose_name='Дата создания')),
                ('date_update', models.CharField(max_length=10, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Карточки пицц',
                'verbose_name_plural': 'Карточки пицц',
                'ordering': ['date_create', 'title'],
            },
        ),
    ]
