# Generated by Django 4.1.3 on 2022-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='pizzaName')),
                ('price', models.PositiveIntegerField()),
                ('modalContent', models.TextField(blank='True')),
                ('isMeat', models.BooleanField(default='True')),
                ('popularity', models.PositiveIntegerField()),
            ],
        ),
    ]
